<?php
/**
 * ParamSet
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Irisnet\APIV2\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Irisnet API
 *
 * Artificial Intelligence (AI) for image- and video-processing in real-time. This is an interactive documentation where you can quickly look up the endpoints and their schemas, while having the opportunity to try things out for yourself.  In the list below, you can see the available endpoints of the API, which can be expanded by clicking on them. Each expanded endpoint lists the request parameters (if available) and the request body (if available). The request body can list some example bodies and the schema, explaining each model in detail.  Additionally you'll find a 'Try it out' button that allows you to enter your custom parameters and custom body and execute that against the API. <b>Be sure to enter your license key to authorize the requests before using this documentation interactively.</b>  The responses section in the expanded endpoint lists the possible responses with their corresponding status codes. If you've executed an API call it will also show you the response from the server.  Underneath the endpoints you'll find the model schemas. These are the models used for the requests and responses. If you click on the right arrow, you can expand the model and get a description of the model and the model parameters. For nested models, you can keep clicking the right arrow for further details.  Clicking the link below the title at the top of this page opens the [OpenAPI specification](https://swagger.io/specification/) (OAS3) in JSON format. The OAS3 Spec allows the generation of clients in many programming languages. There are several free client generators available that can be used to get started easily.
 *
 * The version of the OpenAPI document: v2
 * Contact: info@irisnet.de
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Irisnet\APIV2\Client\Model;

use \ArrayAccess;
use \Irisnet\APIV2\Client\ObjectSerializer;

/**
 * ParamSet Class Doc Comment
 *
 * @category Class
 * @description A set of parameters/rules that describe how the AI should behave.
 * @package  Irisnet\APIV2\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ParamSet implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ParamSet';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'thresh' => 'float',
        'grey' => 'int',
        'min_duration' => 'int',
        'abort_on_severity' => 'int',
        'params' => '\Irisnet\APIV2\Client\Model\Param[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'thresh' => 'float',
        'grey' => 'int32',
        'min_duration' => 'int32',
        'abort_on_severity' => 'int32',
        'params' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'thresh' => false,
		'grey' => false,
		'min_duration' => false,
		'abort_on_severity' => false,
		'params' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'thresh' => 'thresh',
        'grey' => 'grey',
        'min_duration' => 'minDuration',
        'abort_on_severity' => 'abortOnSeverity',
        'params' => 'params'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'thresh' => 'setThresh',
        'grey' => 'setGrey',
        'min_duration' => 'setMinDuration',
        'abort_on_severity' => 'setAbortOnSeverity',
        'params' => 'setParams'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'thresh' => 'getThresh',
        'grey' => 'getGrey',
        'min_duration' => 'getMinDuration',
        'abort_on_severity' => 'getAbortOnSeverity',
        'params' => 'getParams'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('thresh', $data ?? [], 0.5);
        $this->setIfExists('grey', $data ?? [], 127);
        $this->setIfExists('min_duration', $data ?? [], 100);
        $this->setIfExists('abort_on_severity', $data ?? [], -1);
        $this->setIfExists('params', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['thresh']) && ($this->container['thresh'] > 1.0)) {
            $invalidProperties[] = "invalid value for 'thresh', must be smaller than or equal to 1.0.";
        }

        if (!is_null($this->container['thresh']) && ($this->container['thresh'] < 0.0)) {
            $invalidProperties[] = "invalid value for 'thresh', must be bigger than or equal to 0.0.";
        }

        if (!is_null($this->container['grey']) && ($this->container['grey'] > 255)) {
            $invalidProperties[] = "invalid value for 'grey', must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['grey']) && ($this->container['grey'] < 0)) {
            $invalidProperties[] = "invalid value for 'grey', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_duration']) && ($this->container['min_duration'] > 250)) {
            $invalidProperties[] = "invalid value for 'min_duration', must be smaller than or equal to 250.";
        }

        if (!is_null($this->container['min_duration']) && ($this->container['min_duration'] < 50)) {
            $invalidProperties[] = "invalid value for 'min_duration', must be bigger than or equal to 50.";
        }

        if (!is_null($this->container['abort_on_severity']) && ($this->container['abort_on_severity'] < -1)) {
            $invalidProperties[] = "invalid value for 'abort_on_severity', must be bigger than or equal to -1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets thresh
     *
     * @return float|null
     */
    public function getThresh()
    {
        return $this->container['thresh'];
    }

    /**
     * Sets thresh
     *
     * @param float|null $thresh Threshold when an object can be recognized. Lowering the value will increase the probability of recognizing objects. A threshold of 0.5 would mean, that 50% of an object like a face must be visible, to be detected.Setting the value too low however, can cause false positives.
     *
     * @return self
     */
    public function setThresh($thresh)
    {
        if (is_null($thresh)) {
            throw new \InvalidArgumentException('non-nullable thresh cannot be null');
        }

        if (($thresh > 1.0)) {
            throw new \InvalidArgumentException('invalid value for $thresh when calling ParamSet., must be smaller than or equal to 1.0.');
        }
        if (($thresh < 0.0)) {
            throw new \InvalidArgumentException('invalid value for $thresh when calling ParamSet., must be bigger than or equal to 0.0.');
        }

        $this->container['thresh'] = $thresh;

        return $this;
    }

    /**
     * Gets grey
     *
     * @return int|null
     */
    public function getGrey()
    {
        return $this->container['grey'];
    }

    /**
     * Sets grey
     *
     * @param int|null $grey A grey scale color to use for frame or masking. '0' will represent black, while the maximum '255' will be white.
     *
     * @return self
     */
    public function setGrey($grey)
    {
        if (is_null($grey)) {
            throw new \InvalidArgumentException('non-nullable grey cannot be null');
        }

        if (($grey > 255)) {
            throw new \InvalidArgumentException('invalid value for $grey when calling ParamSet., must be smaller than or equal to 255.');
        }
        if (($grey < 0)) {
            throw new \InvalidArgumentException('invalid value for $grey when calling ParamSet., must be bigger than or equal to 0.');
        }

        $this->container['grey'] = $grey;

        return $this;
    }

    /**
     * Gets min_duration
     *
     * @return int|null
     */
    public function getMinDuration()
    {
        return $this->container['min_duration'];
    }

    /**
     * Sets min_duration
     *
     * @param int|null $min_duration Set the overall minimum duration in milliseconds for a rule to be broken in moving images.
     *
     * @return self
     */
    public function setMinDuration($min_duration)
    {
        if (is_null($min_duration)) {
            throw new \InvalidArgumentException('non-nullable min_duration cannot be null');
        }

        if (($min_duration > 250)) {
            throw new \InvalidArgumentException('invalid value for $min_duration when calling ParamSet., must be smaller than or equal to 250.');
        }
        if (($min_duration < 50)) {
            throw new \InvalidArgumentException('invalid value for $min_duration when calling ParamSet., must be bigger than or equal to 50.');
        }

        $this->container['min_duration'] = $min_duration;

        return $this;
    }

    /**
     * Gets abort_on_severity
     *
     * @return int|null
     */
    public function getAbortOnSeverity()
    {
        return $this->container['abort_on_severity'];
    }

    /**
     * Sets abort_on_severity
     *
     * @param int|null $abort_on_severity Set a severity on which to automatically stop the check operation. Works with moving images.Use '-1' to ignore this option.
     *
     * @return self
     */
    public function setAbortOnSeverity($abort_on_severity)
    {
        if (is_null($abort_on_severity)) {
            throw new \InvalidArgumentException('non-nullable abort_on_severity cannot be null');
        }

        if (($abort_on_severity < -1)) {
            throw new \InvalidArgumentException('invalid value for $abort_on_severity when calling ParamSet., must be bigger than or equal to -1.');
        }

        $this->container['abort_on_severity'] = $abort_on_severity;

        return $this;
    }

    /**
     * Gets params
     *
     * @return \Irisnet\APIV2\Client\Model\Param[]|null
     */
    public function getParams()
    {
        return $this->container['params'];
    }

    /**
     * Sets params
     *
     * @param \Irisnet\APIV2\Client\Model\Param[]|null $params A list of parameter sets that describe the rules of the objects.
     *
     * @return self
     */
    public function setParams($params)
    {
        if (is_null($params)) {
            throw new \InvalidArgumentException('non-nullable params cannot be null');
        }
        $this->container['params'] = $params;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


